openapi: 3.0.0
info:
  title: swagger 在线接口平台
  version: 1.0.0
  description: >-
    Swagger是一款RESTful API的文档生成工具，它可以帮助开发者快速、准确地编写、维护和查阅API文档


    Related links:

    - [KoaServer](https://github.com/MFanLiang/EspressoKoaServer)

    - [basic-structure-docs](https://swagger.io/docs/specification/basic-structure/)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
host: localhost:5050
basePath: './'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  response:
    UnauthorizedError:
      description: Protected resource, use Authorization header to get access

tags:
  - name: default-api
    description: sys default API
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: 用户管理
    description: Operations about user
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: 公共模块
    description: Operations about base module
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: 菜单管理
    description: Operations about menu management
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: 文件服务
    description: Operations about File management
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: 业务模块
    description: Operations about General service module
    externalDocs:
      description: Find out more
      url: http://swagger.io
